services:
  - type: web
    name: opus-miniapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web.app:app
    envVars:
      - key: MONGO_URI
        value: 
